### ISSUE TITLE
Flipper app

### ISSUE THREAD

**Issue by ziggyiggi** [Next-Flip/Momentum-Firmware#107] opened 2024-04-23 12:03 UTC
### Describe the bug.

This MAY be the wrong location, but I've recently noticed the flipper zero app store is not compatible with this version of momentum.

![Screenshot_20240423_080108_Flipper](https://github.com/Next-Flip/Momentum-Firmware/assets/157992186/d6c314fa-ed22-4ad3-8dce-571cfe9790a4)
![Screenshot_20240423_080117_Flipper](https://github.com/Next-Flip/Momentum-Firmware/assets/157992186/5f90cb99-414e-4674-945a-41e347fb2159)

### Reproduction

Connect flipper to flipper zero app and go to hub to try and install apps

### Anything else?

Momentum ROCKS!

**Comment by rbartolome** [comment] 2024-04-23 12:33
I did open an issue at the official flipperdevices repo [#3606](https://github.com/flipperdevices/flipperzero-firmware/issues/3606). In general you only see apps if you are running the latest release version. The issue is closed by flipperdevices.

**Comment by ziggyiggi** [comment] 2024-04-23 12:45
Ah! Just noticed I'd accidentally installed  the dev version. Apologies!

**Closed as completed** 2024-04-23 20:17 UTC
Labels: question
