### ISSUE TITLE
Add frequency discression to frequency analyzer

### ISSUE THREAD

**Issue by X3r0C00L** [Next-Flip/Momentum-Firmware#123] opened 2024-05-15 16:14 UTC
### Description of the feature you're suggesting.

I have some low frequency towers near me that transmit in the mid 300 and mid 400mhz bands and when Im using the flipper to analyze signals near me these signals are so strong that they overpower any other signals im trying to locate (using the flux capacitor). 
Could a feature be added to the frequency analyzer app to allow one to put in certain frequencies to skip when scanning the spectrum? this would make a huge difference in my ability to test the environments around me. 

### Anything else?

Thank you all for all the great work. You are appreciated.

**Comment by WillyJL** [comment] 2024-05-17 20:40
Now that I think about it, you might be able to do this via Momentum > Protocols > SubGhz freqs.

Frequency analyzer uses the same list of frequencies as read does, as far as I know. So you could set Use Defaults to off, then add the frequencies you want to check inside the Static Freqs > Add static freq

**Comment by WillyJL** [comment] 2024-05-18 06:38
actually a duplicate of #43, i will post the same thought i had there

**Closed as completed by WillyJL** 2024-05-18 06:38 UTC
Labels: duplicate, feature

**Comment by Cub4nH1** [comment] 2025-10-03 14:54
Thanks for the clarification — much appreciated! I confirmed `rolling_counter` is present in the saved .sub file, so this solves my question. Closing the issue. Thanks again for the quick response and the great project.
